version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - diogopms

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - diogopms
